### ISSUE TITLE
Support for html-js AJAX request

### ISSUE THREAD

**Issue by tiredenzo** [Adyen/client-side-encryption#19]
Hello Adyen guys

I have added to adyen.encrypt.js the feature to directly encrypt a javascript object so i can submit it via AJAX
I will not do a pull request on this as the code I did is a bit hacky and it would take you 3 seconds to do the same cleaner with better code reuse.

To sum up: It would be great if you guys add the support for CSE on javascript object without validations and without submitting the form

BTW I use angularJS... A lot of people do and this feature would be greatly appreciated by your potential customers

Stripe's JS library is a bit more developer friendly I think. You should just add this feature and it would be really perfect for a client side use!

Thanks a lot for your work and keep up the pace dudes !

**Comment by tiredenzo** [comment]
Just so you know I have added createEncryptedObject
`````
    var encrypt = adyen.encrypt = adyen.encrypt || {
        createEncryptedForm : function ( form, key, options ) {
            return new EncryptedForm( form, key, options );
        },
        createEncryptedObject : function(obj, key) {
            return EncryptedObject(obj, key);
        }
    };
`````
and EncryptedObject
`````
    var EncryptedObject = function(object, key) {
        try {
            sjcl.random.startCollectors();
        } catch ( e ) {
            // what to do?
        }

        var createRSAKey = function () {

            var k = key.split( '|' );

            if ( k.length != 2 ) {
                throw 'Malformed public key';
            }

            var exp = k[ 0 ];
            var mod = k[ 1 ];

            // would be better to put it in a package.
            var rsa = new RSAKey();
            rsa.setPublic( mod, exp );

            return rsa;

        }

        var encrypt = function() {
    
            var data = object;
            // beware array object ?

            var rsa, aes, cipher, keybytes, encrypted, prefix;

            rsa = createRSAKey();
            aes = new AESKey();

            cipher = aes.encrypt( JSON.stringify( data ) );
            keybytes = sjcl.codec.bytes.fromBits( aes.key );
            encrypted = rsa.encrypt_b64( keybytes );
            prefix = 'adyenjs_' + adyen.encrypt.version + '$';

            return [ prefix, encrypted, '$', cipher ].join( '' );

        }

        return encrypt();
    }
`````

**Comment by ArnoudAdyen** [comment]
Hi Enzo,

I think the current is already possible by using a combination of the options.onsubmit and options.enableValidations. The first one isn't documented properly I notice, which I will amend in a upcoming release.

// Disable validations
options.enableValidations = false;

// Cancel submit
options.onsubmit = function(ev) {
  ev.preventDefault();
};

Can you see if this works in your scenario as well?

Kind regards,

Arnoud

**Comment by tiredenzo** [comment]
The thing is that with AngularJS I prefer to have access to the "name" attribute. they are used for validations. (yes i could still hack my way out with the data-enrypted-* attributes) using this technique

I also prefer to access the encrypted data directly returned by a function rather than taking it from the DOM that would be altered by adyen's lib.

To sum up... think about a javascript client with no HTML DOM... in my opinion it should also work directly in pure JS (android phonegap node.js, QT5 app or wathever...)
It would be great if you could just break the encryption/dom dependency as javascript is sadly :-1:  running kind of everywhere now... sad story bro... sad story yeak I know :'(

Now My Little Story:
You may want to know why I did all this as I have a ruby on rails app XD and (as I do have a DOM huhuh XD) (im a lucky bastard)

For the simple reason I did not want the credit card fields to come back blank upon a normal server form submission if an error occurred during payment (as they are encrypted fields they cannot be redisplayed from the server's html rendering)....
So... That would clearly drop my conversions :)

So yes maybe this method would work....
But I would not suggest in a long term :)

Thanks for such a fast reply mate !!!

**Comment by ArnoudAdyen** [comment]
Hi Enzo,

The whole point of the name attributes not being there is that for PCI compliancy the credit card details are not allowed to reach your server as plain values. If you are changing your code in a way that it does reach your server, you might be in violation of PCI.

Offering a way for you to return the encrypted data back into the JavaScript to put them in the form would also not be possible as then the private key will be exposed to the browser, defeating the purpose of the encryption.

Kind regards,

Arnoud

**Comment by tiredenzo** [comment]
Hello... of course NONE of those data are transmitted to my server i do not think you understood my point
I suggest you break encryption/dom dependency thats it

**Comment by tiredenzo** [comment]
Using AngularJS names are NOT transmitting nothing to server :) I know my libs don't worry.
we use 'ng-model' attributes for this purpose. Web is evolving fast this is why I suggest you break this depedency

**Comment by tiredenzo** [comment]
Just forgot about the name thing...
Just keep this

Think about a javascript client with no HTML DOM... in my opinion it should also work directly in pure JS (android phonegap, node.js, QT5 app or wathever...)

**Comment by tiredenzo** [comment]
I can give you a skype call if not. What i suggest i think really is important for your library.

**Comment by tiredenzo** [comment]
If I could say it another way: forget about the HTML forms. Some people would eventually like to implement CSE with a JS XML-RPC or an Apache Thrift or JSON or XML or SOAP or whatever...

To achieve this purposes it would be great to break dependency on DOM thats it.

**Comment by tiredenzo** [comment]
Hello

To reply to the first point

Using AngularJS names are NOT transmitting nothing to server :) They are only used for client side model validation purposes. I know my frameworks don't worry.
we use 'ng-model' directives for this purpose. Web is evolving fast this is why I suggest you break this depedency. names do not act as you think with some JS frameworks that extend HTML do a DSL.

I can give you a skype call if you still have a doubt. What i suggest i think really is important for your library. It's just a matter to give a bit more of freedom on the implementation. The current library only allows for normal HTML forms to be submitted. Hipster JS forms do not work the way normal HTML forms work as HTML becomes a DSL

If I could say it another way: forget about the HTML forms. Some people would eventually like to implement CSE with a JS XML-RPC or an Apache Thrift or JSON or XML or SOAP or whatever...

To achieve this purposes it would be great to break dependency on encryption/DOM

Second point

Yes i know :)

**Comment by tiredenzo** [comment]
Imagine I would like to implement adyen cse in HTML - JS... and
the webservice that i'm communicating to is only available via XML/RPC ?
You see where i want to get ?

**Comment by ArnoudAdyen** [comment]
Hi Enzo,

I understand what you are saying, but have to look more broadly. I can look into offering a more decoupled interface, but that comes with the cost that we can do less scanning for PCI compliancy and prevent that less tech savvy people run into issues by implementation mistakes.

Even in advanced web based implementations there are always form fields that are being used by shoppers that need to be filled out and which together need to be encrypted. Yes you might want to do the boiler-plating yourself, but for a average developer there shouldn't be a need to.

You seem to be a more than average developer and you require more plugin points and hook. We'll look into that. As I cannot promise a delivery date, for now the XML/RPC can probably only be called from the before mentioned onsubmit option. You can do the binding of the Encrypted form in a angular directive's link. This might not be fully compliant with the desired angular setup, but that is something we can work on.

Regards,

Arnoud

**Comment by tiredenzo** [comment]
Maybe a decoupled interface would be great.
but also to keep it simple is a priority indeed !

Your platform and support really rocks.
You are doing a great work.... really

Thank you Arnoud and have a nice day

**Comment by ArnoudAdyen** [comment]
Enzo,

Please look into the latest version of the CSE. It took way longer than I had anticipated, but I hope it will also cater for your needs. If not, please let us know from the new repository location:

https://github.com/Adyen/CSE-JS

Kind regards,

Arnoud

**Comment by tiredenzo** [comment]
Thanks so much it is perfect !
