### ISSUE TITLE
Separate repos per language and add Bower

### ISSUE THREAD

**Issue by Rvanlaak** [Adyen/client-side-encryption#20]
Hi guys, I'd like integrate the CSE library using Bower to keep it up-to-date. We do not like checking in external libraries in our own code ;-)

Unfortunately this repo contains all different sorts of languages. Can you please make separate repos per language? Or otherwise move the examples (php,java,rails?) to an /examples folder?

So that would become:
https://github.com/Adyen/client-side-encryption-js
https://github.com/Adyen/client-side-encryption-android
https://github.com/Adyen/client-side-encryption-ios
https://github.com/Adyen/client-side-encryption-windowsphone

Next step would be to [create a package ](http://bower.io/docs/creating-packages/) or copy the bower.json file from the fork that already exists https://github.com/maetolay/adyen-js

**Comment by rngtng** [comment]
:+1: makes sense

**Comment by Rvanlaak** [comment]
Ping @adyenpayments @xslim

**Comment by leafymind** [comment]
:+1:

**Comment by xslim** [comment]
https://github.com/Adyen/CSE-iOS ?

**Comment by Rvanlaak** [comment]
That repo is a great start for separating the iOS code from this repo. In my opinion the separation should happen for the Android an Windows Phone code as well. 

In other words, thereafter the iOS, Android and Windows Phone code can be removed from this repository. That will result in this repo being a codebase for solely the html-js code and then it can be required using Bower (as mentioned earlier).

**Comment by xslim** [comment]
https://github.com/Adyen/CSE-JS
You are welcome to Fork and propose the bower.json file

**Comment by xslim** [comment]
Also, tag `0.1.10` created

**Comment by ArnoudAdyen** [comment]
@Rvanlaak Please know that we are working to get the CSE-JS hosted from the Adyen HPP servers with the Public Key embedded. The whole embedding procedure will then change if you decide to take that route. This will allow us to start working with automatic keyrolling and push critical bugfixes easier.

If you want to play around you should be able to get the URL to the hosted CSE from the Webservice user page in the Customer Area. Note that the calling code is slightly different as the Public Key is no longer a parameter.

**Comment by Rvanlaak** [comment]
Added the PR for the bower.json and registered it to the Bower Heroku repository. :+1: 

A hosted version of the CSE library sounds great, but the release of that will probably be later than our implementation timeframe of two weeks right?
