### ISSUE TITLE
adyen.encrypt.nodom.min.js not working on Cordova IOs

### ISSUE THREAD

**Issue by VanHumbeeckA** [Adyen/client-side-encryption#24]
I included the 'adyen.encrypt.nodom.min.js' file in our cordova application.
Everything works on android devices.

But we get errors on all iOS devices.
Any idea what's going on?
Stack traces in the console:

Error: undefined is not an object (evaluating 'this.key.split')
createRSAKey@file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/vendor/adyen.encrypt.nodom.min.js:21:16494
encrypt@file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/vendor/adyen.encrypt.nodom.min.js:21:17150
q@file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/scripts/scripts.js:3:16337
s@file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/scripts/scripts.js:3:16998
fn
file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/scripts/vendor.js:16:11378
$eval@file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/scripts/vendor.js:5:28167
$apply@file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/scripts/vendor.js:5:28398
file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/scripts/vendor.js:16:11365
dispatch@file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/scripts/vendor.js:2:16712
handle@file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/scripts/vendor.js:2:14785
dispatchEvent@[native code]
c@file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/scripts/vendor.js:10:9546
b@file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/scripts/vendor.js:10:9366
i@file:///var/containers/Bundle/Application/1A2EBED1-314F-47F4-819D-60FC50347166/Hubert-DEV-DEV.app/www/scripts/vendor.js:10:10601
(anonymous function)vendor.js:4184
(anonymous function)vendor.js:3408
$applyvendor.js:4677
(anonymous function)vendor.js:16965
dispatchvendor.js:613
handlevendor.js:544
dispatchEvent
cvendor.js:10915:359
bvendor.js:10915:158
ivendor.js:10915:1461

**Comment by VanHumbeeckA** [comment]
I was on version 1.16.
I now upgraded the file to the one of version 1.17

Still got the same stack traces: 

Error: undefined is not an object (evaluating 'this.key.split')
createRSAKey@file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/vendor/adyen.encrypt.nodom.min.js:14:18031
encrypt@file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/vendor/adyen.encrypt.nodom.min.js:14:18687
q@file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/scripts/scripts.js:3:16337
t@file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/scripts/scripts.js:3:17027
fn
file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/scripts/vendor.js:16:11378
$eval@file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/scripts/vendor.js:5:28167
$apply@file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/scripts/vendor.js:5:28398
file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/scripts/vendor.js:16:11365
dispatch@file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/scripts/vendor.js:2:16712
handle@file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/scripts/vendor.js:2:14785
dispatchEvent@[native code]
c@file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/scripts/vendor.js:10:9546
b@file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/scripts/vendor.js:10:9366
i@file:///var/containers/Bundle/Application/71490489-9A55-4725-8A8B-84ABE6D9B109/Hubert-DEV-DEV.app/www/scripts/vendor.js:10:10601
(anonymous function)vendor.js:4:13829
(anonymous function)vendor.js:3:31588
$applyvendor.js:4:28412
(anonymous function)vendor.js:15:11365
dispatchvendor.js:1:16712
handlevendor.js:1:14785
dispatchEvent
cvendor.js:9:9546
bvendor.js:9:9366
ivendor.js:9:10601

**Comment by ArnoudAdyen** [comment]
Hi,

Technical Support will get back to you on your ticket.

- Arnoud

**Comment by VanHumbeeckA** [comment]
Ok, thanks. 
Hope to know more soon, since this is really a blocking issue for our entire application.
I also logged this as a support ticket. With ID: LPC-669-89689

**Comment by VanHumbeeckA** [comment]
I found out what the exact problem was.
It was due to an environment variable not set on our build-mac,
which in turn did not fill in the 'key'-param for the adyen.encrypt.creatEncryption(key, options).

Hence the error "undefined is not an object (evaluating 'this.key.split')"
--> he tried to split the key on a '|' character.
